### ISSUE TITLE
cairo library erro

### ISSUE THREAD

**Issue by circuitmamu** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#7]
`PS D:\laragon\www\nvs\divagicha> python schedule_vaccination_appointment.py
Traceback (most recent call last):
  File "schedule_vaccination_appointment.py", line 7, in <module>
    from CovidVaccineChecker import TextColors, CoWINAPI
  File "D:\laragon\www\nvs\divagicha\CovidVaccineChecker\__init__.py", line 13, in <module>
    from CovidVaccineChecker.captcha import captcha_builder
  File "D:\laragon\www\nvs\divagicha\CovidVaccineChecker\captcha.py", line 7, in <module>
    from cairosvg import svg2png
  File "C:\Users\PC11\AppData\Local\Programs\Python\Python37\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\PC11\AppData\Local\Programs\Python\Python37\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\PC11\AppData\Local\Programs\Python\Python37\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "C:\Users\PC11\AppData\Local\Programs\Python\Python37\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e`

**Comment by divagicha** [comment]
This issue is raised when the system does not know where to look for the required DLLs. Make sure your DLL files location is added to the PATH environment variable. Alternatively, you can also download the latest exe from this [link](https://github.com/DivAgicha/CoWIN-Vaccine-Appointment-Booking/raw/master/dist/CovidVaccinationAppointmentScheduler-Setup-v2.1.exe), as everything is already pre-packed into the exe file. Let me know if the program runs without any errors.

**Comment by divagicha** [comment]
UPDATE: as per the new update, captcha has been removed from the scheduling process. So, all the related modules have now been removed from use in the script as well, including 'cairosvg'. You can pull the latest code and try running the script.

Kindly let me know if the script worked on your end and if this issue can be closed now.

**Comment by divagicha** [comment]
Due to no activity/response from your end, this issue will now be closed.
